name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install linting tools
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format clang-tidy
    
    - name: Check formatting
      run: |
        find . -name '*.cpp' -o -name '*.hpp' | xargs clang-format --style=Google -n -Werror
    
    - name: Run clang-tidy
      run: |
        # Run clang-tidy on all cpp files
        find . -name '*.cpp' | xargs clang-tidy -p build