name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install linting tools
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format clang-tidy
    
    - name: Check formatting
      run: |
        find . -name '*.cpp' -o -name '*.h' | xargs clang-format --style=Google -n -Werror
    
    - name: Run clang-tidy
      run: |
        # Generate compile_commands.json
        cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        
        # Run clang-tidy on all cpp files
        find . -name '*.cpp' | xargs clang-tidy -p build

  test:
    runs-on: ubuntu-latest
    needs: lint  # Run after linting passes
    
    container:
      # Using a placeholder image name - replace with your actual image once created
      image: xilinx/vitis-hls:2023.1
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run tests
      run: |
        chmod +x ./test.sh
        ./test.sh 